open:
  Monday: true
  Tuesday: false
  Wednesday: true
  Thursday: true
  Friday: true
  Saturday: true
  Sunday: false

holiday:
  - 12/25
  - 07/14
  - 01/01
#-------------------------------
#date qui varie selon les années
#-------------------------------
#
#pentecote
  - 2020/06/01
  - 2021/05/24