capacity: 1000

open:
  Monday: true
  Tuesday: false
  Wednesday: true
  Thursday: true
  Friday: true
  Saturday: true
  Sunday: false

holiday:
#Jour de l'an
  - 01/01
#Pâques
  - 04/13
#Fête du travail
  - 05/01
#Vitoire des alliés en 1945
  - 05/08
#Fête nationale
  - 07/14
#Noël
  - 12/25


#-------------------------------
#date qui varie selon les années
#-------------------------------
#
#pentecote
  - 2020/06/01
  - 2021/05/24